title: Drone-Art
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5042965
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#000008'
    - '#5b718c'
    - '#ffffff'
    - '#9da0a6'
    - '#d4ccbe'
  rhythmicContrast: 0.4989259
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: drone-art.ch
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.32419
layout_spectrum: 1
