name: drone-art.ch
favicon: null
layout_spectrum: 0.12142450944520533
typography_spectrum: 0.11212639044970274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.585528866155073
  lightness: 0.05584627320058644
  saturation: 0.8104138078633696
  rhythmicContrast: 0.6994693190790713
purpose: []
