name: drone-art.ch
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32419
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffedd8'
    - '#051f12'
    - '#5b5241'
    - '#a6b8a6'
    - '#a28367'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
