name: drone-art.ch
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32419
title: Drone-Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000008'
    - '#5b718c'
    - '#ffffff'
    - '#9da0a6'
    - '#d4ccbe'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
